# Generated by Django 5.2.12 on 2026-04-07 17:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'scholarship_categories',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_email', models.EmailField(max_length=255)),
                ('education_level', models.CharField(blank=True, choices=[('SMA/SMK', 'SMA/SMK'), ('D3', 'D3'), ('D4/S1', 'D4/S1'), ('S2', 'S2'), ('S3', 'S3'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('coverage_type', models.CharField(choices=[('FULL_FUNDED', 'Full Funded'), ('PARTIAL_FUNDED', 'Partial Funded'), ('ALLOWANCE_ONLY', 'Allowance Only')], default='FULL_FUNDED', max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, default='')),
                ('external_link', models.URLField(max_length=2048)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='scholarship_posters/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scholarships',
                'ordering': ['-created_at'],
            },
        ),
    ]
